/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AiScoreFactors {
  'behaviorScore' : number,
  'totalKm' : number,
  'issueCount' : bigint,
  'workingDays' : bigint,
}
export interface Issue { 'flag' : IssueFlag, 'description' : string }
export type IssueFlag = { 'Safety' : null } |
  { 'Software' : null } |
  { 'Mechanical' : null } |
  { 'Performance' : null } |
  { 'Electrical' : null } |
  { 'Other' : null };
export type ModelId = bigint;
export type RecordId = bigint;
export interface RiderRating {
  'adminRating' : [] | [bigint],
  'username' : string,
  'adminRatingComment' : [] | [string],
  'aiScoreTimestamp' : [] | [Timestamp],
  'aiScore' : [] | [number],
  'aiScoreFactors' : [] | [AiScoreFactors],
  'adminRatingTimestamp' : [] | [Timestamp],
}
export interface Route {
  'id' : RouteId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'distanceKm' : number,
}
export type RouteId = bigint;
export type TestPurpose = { 'ComponentTest' : null } |
  { 'Range' : null } |
  { 'Durability' : null } |
  { 'Others' : string };
export interface TestRecord {
  'id' : RecordId,
  'photoUrls' : Array<string>,
  'rangeStartKm' : number,
  'vehicleModelName' : string,
  'startSoc' : [] | [number],
  'stopSoc' : [] | [number],
  'createdBy' : Principal,
  'coRiderWeight' : [] | [number],
  'vehicleModelId' : ModelId,
  'routeName' : string,
  'testingMode' : [] | [TestingMode],
  'issues' : Array<Issue>,
  'customRoute' : [] | [string],
  'routeId' : RouteId,
  'rangeStopKm' : number,
  'topSpeedKmh' : number,
  'testPurpose' : [] | [TestPurpose],
  'timestamp' : Timestamp,
  'riderName' : string,
  'avgSpeedKmh' : number,
  'dateOfRide' : [] | [Timestamp],
  'riderWeight' : [] | [number],
}
export type TestingMode = { 'Eco' : null } |
  { 'Sport' : null } |
  { 'City' : null } |
  { 'Other' : string };
export type Timestamp = bigint;
export interface UserProfile {
  'adminRating' : [] | [bigint],
  'principal' : Principal,
  'username' : [] | [string],
  'adminRatingComment' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'passwordHash' : [] | [string],
  'aiScoreTimestamp' : [] | [Timestamp],
  'aiScore' : [] | [number],
  'aiScoreFactors' : [] | [AiScoreFactors],
  'adminRatingTimestamp' : [] | [Timestamp],
}
export type UserRole = { 'Rider' : null } |
  { 'Analyst' : null } |
  { 'Admin' : null };
export interface VehicleModel {
  'id' : ModelId,
  'vehicleType' : VehicleType,
  'name' : string,
  'createdAt' : Timestamp,
  'specs' : string,
}
export type VehicleType = { 'TwoWheeler' : null } |
  { 'ThreeWheeler' : null };
export interface _SERVICE {
  'addRoute' : ActorMethod<
    [string, string, number],
    { 'ok' : Route } |
      { 'err' : string }
  >,
  'addVehicleModel' : ActorMethod<
    [string, VehicleType, string],
    { 'ok' : VehicleModel } |
      { 'err' : string }
  >,
  'adminCreateTestRecord' : ActorMethod<
    [
      ModelId,
      RouteId,
      string,
      number,
      number,
      [] | [number],
      [] | [number],
      number,
      number,
      Array<Issue>,
      [] | [Array<string>],
      [] | [TestingMode],
      [] | [string],
      [] | [number],
      [] | [number],
      [] | [TestPurpose],
      [] | [bigint],
    ],
    { 'ok' : TestRecord } |
      { 'err' : string }
  >,
  'changePassword' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createUserByAdmin' : ActorMethod<
    [string, string, string, UserRole],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'deleteRoute' : ActorMethod<
    [RouteId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteTestRecord' : ActorMethod<
    [RecordId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteUser' : ActorMethod<
    [Principal],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteUserByUsername' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteVehicleModel' : ActorMethod<
    [ModelId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getRiderRating' : ActorMethod<
    [string],
    { 'ok' : [] | [RiderRating] } |
      { 'err' : string }
  >,
  'getRoute' : ActorMethod<[RouteId], [] | [Route]>,
  'getTestRecord' : ActorMethod<
    [RecordId],
    { 'ok' : [] | [TestRecord] } |
      { 'err' : string }
  >,
  'getTopIssues' : ActorMethod<
    [bigint],
    { 'ok' : Array<[IssueFlag, bigint]> } |
      { 'err' : string }
  >,
  'getUserByUsername' : ActorMethod<[string], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVehicleModel' : ActorMethod<[ModelId], [] | [VehicleModel]>,
  'listAllUsers' : ActorMethod<
    [],
    { 'ok' : Array<UserProfile> } |
      { 'err' : string }
  >,
  'listRoutes' : ActorMethod<[], Array<Route>>,
  'listTestRecords' : ActorMethod<
    [],
    { 'ok' : Array<TestRecord> } |
      { 'err' : string }
  >,
  'listTestRecordsByModel' : ActorMethod<
    [ModelId],
    { 'ok' : Array<TestRecord> } |
      { 'err' : string }
  >,
  'listTestRecordsByRider' : ActorMethod<
    [string],
    { 'ok' : Array<TestRecord> } |
      { 'err' : string }
  >,
  'listTestRecordsByRoute' : ActorMethod<
    [RouteId],
    { 'ok' : Array<TestRecord> } |
      { 'err' : string }
  >,
  'listVehicleModels' : ActorMethod<[], Array<VehicleModel>>,
  'loginWithCredentials' : ActorMethod<
    [string, string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'recalculateRiderRating' : ActorMethod<
    [string],
    { 'ok' : RiderRating } |
      { 'err' : string }
  >,
  'registerSelf' : ActorMethod<
    [string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'setAdminRatingForRider' : ActorMethod<
    [string, bigint, [] | [string]],
    { 'ok' : RiderRating } |
      { 'err' : string }
  >,
  'submitTestRecord' : ActorMethod<
    [
      ModelId,
      RouteId,
      string,
      number,
      number,
      [] | [number],
      [] | [number],
      number,
      number,
      Array<Issue>,
      [] | [Array<string>],
      [] | [TestingMode],
      [] | [string],
      [] | [number],
      [] | [number],
      [] | [TestPurpose],
      [] | [bigint],
    ],
    { 'ok' : TestRecord } |
      { 'err' : string }
  >,
  'updateUserRole' : ActorMethod<
    [Principal, UserRole],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'updateUserRoleByUsername' : ActorMethod<
    [string, UserRole],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];