/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RouteId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Route = IDL.Record({
  'id' : RouteId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'distanceKm' : IDL.Float64,
});
export const VehicleType = IDL.Variant({
  'TwoWheeler' : IDL.Null,
  'ThreeWheeler' : IDL.Null,
});
export const ModelId = IDL.Nat;
export const VehicleModel = IDL.Record({
  'id' : ModelId,
  'vehicleType' : VehicleType,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'specs' : IDL.Text,
});
export const IssueFlag = IDL.Variant({
  'Safety' : IDL.Null,
  'Software' : IDL.Null,
  'Mechanical' : IDL.Null,
  'Performance' : IDL.Null,
  'Electrical' : IDL.Null,
  'Other' : IDL.Null,
});
export const Issue = IDL.Record({
  'flag' : IssueFlag,
  'description' : IDL.Text,
});
export const TestingMode = IDL.Variant({
  'Eco' : IDL.Null,
  'Sport' : IDL.Null,
  'City' : IDL.Null,
  'Other' : IDL.Text,
});
export const TestPurpose = IDL.Variant({
  'ComponentTest' : IDL.Null,
  'Range' : IDL.Null,
  'Durability' : IDL.Null,
  'Others' : IDL.Text,
});
export const RecordId = IDL.Nat;
export const TestRecord = IDL.Record({
  'id' : RecordId,
  'photoUrls' : IDL.Vec(IDL.Text),
  'rangeStartKm' : IDL.Float64,
  'vehicleModelName' : IDL.Text,
  'startSoc' : IDL.Opt(IDL.Float64),
  'stopSoc' : IDL.Opt(IDL.Float64),
  'createdBy' : IDL.Principal,
  'coRiderWeight' : IDL.Opt(IDL.Float64),
  'vehicleModelId' : ModelId,
  'routeName' : IDL.Text,
  'testingMode' : IDL.Opt(TestingMode),
  'issues' : IDL.Vec(Issue),
  'customRoute' : IDL.Opt(IDL.Text),
  'routeId' : RouteId,
  'rangeStopKm' : IDL.Float64,
  'topSpeedKmh' : IDL.Float64,
  'testPurpose' : IDL.Opt(TestPurpose),
  'timestamp' : Timestamp,
  'riderName' : IDL.Text,
  'avgSpeedKmh' : IDL.Float64,
  'dateOfRide' : IDL.Opt(Timestamp),
  'riderWeight' : IDL.Opt(IDL.Float64),
});
export const UserRole = IDL.Variant({
  'Rider' : IDL.Null,
  'Analyst' : IDL.Null,
  'Admin' : IDL.Null,
});
export const AiScoreFactors = IDL.Record({
  'behaviorScore' : IDL.Float64,
  'totalKm' : IDL.Float64,
  'issueCount' : IDL.Nat,
  'workingDays' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'adminRating' : IDL.Opt(IDL.Nat),
  'principal' : IDL.Principal,
  'username' : IDL.Opt(IDL.Text),
  'adminRatingComment' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'passwordHash' : IDL.Opt(IDL.Text),
  'aiScoreTimestamp' : IDL.Opt(Timestamp),
  'aiScore' : IDL.Opt(IDL.Float64),
  'aiScoreFactors' : IDL.Opt(AiScoreFactors),
  'adminRatingTimestamp' : IDL.Opt(Timestamp),
});
export const RiderRating = IDL.Record({
  'adminRating' : IDL.Opt(IDL.Nat),
  'username' : IDL.Text,
  'adminRatingComment' : IDL.Opt(IDL.Text),
  'aiScoreTimestamp' : IDL.Opt(Timestamp),
  'aiScore' : IDL.Opt(IDL.Float64),
  'aiScoreFactors' : IDL.Opt(AiScoreFactors),
  'adminRatingTimestamp' : IDL.Opt(Timestamp),
});

export const idlService = IDL.Service({
  'addRoute' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Variant({ 'ok' : Route, 'err' : IDL.Text })],
      [],
    ),
  'addVehicleModel' : IDL.Func(
      [IDL.Text, VehicleType, IDL.Text],
      [IDL.Variant({ 'ok' : VehicleModel, 'err' : IDL.Text })],
      [],
    ),
  'adminCreateTestRecord' : IDL.Func(
      [
        ModelId,
        RouteId,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Float64,
        IDL.Float64,
        IDL.Vec(Issue),
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(TestingMode),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(TestPurpose),
        IDL.Opt(IDL.Int),
      ],
      [IDL.Variant({ 'ok' : TestRecord, 'err' : IDL.Text })],
      [],
    ),
  'changePassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createUserByAdmin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, UserRole],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'deleteRoute' : IDL.Func(
      [RouteId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteTestRecord' : IDL.Func(
      [RecordId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteUserByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteVehicleModel' : IDL.Func(
      [ModelId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getRiderRating' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Opt(RiderRating), 'err' : IDL.Text })],
      ['query'],
    ),
  'getRoute' : IDL.Func([RouteId], [IDL.Opt(Route)], ['query']),
  'getTestRecord' : IDL.Func(
      [RecordId],
      [IDL.Variant({ 'ok' : IDL.Opt(TestRecord), 'err' : IDL.Text })],
      ['query'],
    ),
  'getTopIssues' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Variant({
          'ok' : IDL.Vec(IDL.Tuple(IssueFlag, IDL.Nat)),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getUserByUsername' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVehicleModel' : IDL.Func([ModelId], [IDL.Opt(VehicleModel)], ['query']),
  'listAllUsers' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(UserProfile), 'err' : IDL.Text })],
      ['query'],
    ),
  'listRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
  'listTestRecords' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(TestRecord), 'err' : IDL.Text })],
      ['query'],
    ),
  'listTestRecordsByModel' : IDL.Func(
      [ModelId],
      [IDL.Variant({ 'ok' : IDL.Vec(TestRecord), 'err' : IDL.Text })],
      ['query'],
    ),
  'listTestRecordsByRider' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(TestRecord), 'err' : IDL.Text })],
      ['query'],
    ),
  'listTestRecordsByRoute' : IDL.Func(
      [RouteId],
      [IDL.Variant({ 'ok' : IDL.Vec(TestRecord), 'err' : IDL.Text })],
      ['query'],
    ),
  'listVehicleModels' : IDL.Func([], [IDL.Vec(VehicleModel)], ['query']),
  'loginWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'recalculateRiderRating' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : RiderRating, 'err' : IDL.Text })],
      [],
    ),
  'registerSelf' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'setAdminRatingForRider' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : RiderRating, 'err' : IDL.Text })],
      [],
    ),
  'submitTestRecord' : IDL.Func(
      [
        ModelId,
        RouteId,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Float64,
        IDL.Float64,
        IDL.Vec(Issue),
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(TestingMode),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(TestPurpose),
        IDL.Opt(IDL.Int),
      ],
      [IDL.Variant({ 'ok' : TestRecord, 'err' : IDL.Text })],
      [],
    ),
  'updateUserRole' : IDL.Func(
      [IDL.Principal, UserRole],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updateUserRoleByUsername' : IDL.Func(
      [IDL.Text, UserRole],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RouteId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Route = IDL.Record({
    'id' : RouteId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'distanceKm' : IDL.Float64,
  });
  const VehicleType = IDL.Variant({
    'TwoWheeler' : IDL.Null,
    'ThreeWheeler' : IDL.Null,
  });
  const ModelId = IDL.Nat;
  const VehicleModel = IDL.Record({
    'id' : ModelId,
    'vehicleType' : VehicleType,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'specs' : IDL.Text,
  });
  const IssueFlag = IDL.Variant({
    'Safety' : IDL.Null,
    'Software' : IDL.Null,
    'Mechanical' : IDL.Null,
    'Performance' : IDL.Null,
    'Electrical' : IDL.Null,
    'Other' : IDL.Null,
  });
  const Issue = IDL.Record({ 'flag' : IssueFlag, 'description' : IDL.Text });
  const TestingMode = IDL.Variant({
    'Eco' : IDL.Null,
    'Sport' : IDL.Null,
    'City' : IDL.Null,
    'Other' : IDL.Text,
  });
  const TestPurpose = IDL.Variant({
    'ComponentTest' : IDL.Null,
    'Range' : IDL.Null,
    'Durability' : IDL.Null,
    'Others' : IDL.Text,
  });
  const RecordId = IDL.Nat;
  const TestRecord = IDL.Record({
    'id' : RecordId,
    'photoUrls' : IDL.Vec(IDL.Text),
    'rangeStartKm' : IDL.Float64,
    'vehicleModelName' : IDL.Text,
    'startSoc' : IDL.Opt(IDL.Float64),
    'stopSoc' : IDL.Opt(IDL.Float64),
    'createdBy' : IDL.Principal,
    'coRiderWeight' : IDL.Opt(IDL.Float64),
    'vehicleModelId' : ModelId,
    'routeName' : IDL.Text,
    'testingMode' : IDL.Opt(TestingMode),
    'issues' : IDL.Vec(Issue),
    'customRoute' : IDL.Opt(IDL.Text),
    'routeId' : RouteId,
    'rangeStopKm' : IDL.Float64,
    'topSpeedKmh' : IDL.Float64,
    'testPurpose' : IDL.Opt(TestPurpose),
    'timestamp' : Timestamp,
    'riderName' : IDL.Text,
    'avgSpeedKmh' : IDL.Float64,
    'dateOfRide' : IDL.Opt(Timestamp),
    'riderWeight' : IDL.Opt(IDL.Float64),
  });
  const UserRole = IDL.Variant({
    'Rider' : IDL.Null,
    'Analyst' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const AiScoreFactors = IDL.Record({
    'behaviorScore' : IDL.Float64,
    'totalKm' : IDL.Float64,
    'issueCount' : IDL.Nat,
    'workingDays' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'adminRating' : IDL.Opt(IDL.Nat),
    'principal' : IDL.Principal,
    'username' : IDL.Opt(IDL.Text),
    'adminRatingComment' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'passwordHash' : IDL.Opt(IDL.Text),
    'aiScoreTimestamp' : IDL.Opt(Timestamp),
    'aiScore' : IDL.Opt(IDL.Float64),
    'aiScoreFactors' : IDL.Opt(AiScoreFactors),
    'adminRatingTimestamp' : IDL.Opt(Timestamp),
  });
  const RiderRating = IDL.Record({
    'adminRating' : IDL.Opt(IDL.Nat),
    'username' : IDL.Text,
    'adminRatingComment' : IDL.Opt(IDL.Text),
    'aiScoreTimestamp' : IDL.Opt(Timestamp),
    'aiScore' : IDL.Opt(IDL.Float64),
    'aiScoreFactors' : IDL.Opt(AiScoreFactors),
    'adminRatingTimestamp' : IDL.Opt(Timestamp),
  });
  
  return IDL.Service({
    'addRoute' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Variant({ 'ok' : Route, 'err' : IDL.Text })],
        [],
      ),
    'addVehicleModel' : IDL.Func(
        [IDL.Text, VehicleType, IDL.Text],
        [IDL.Variant({ 'ok' : VehicleModel, 'err' : IDL.Text })],
        [],
      ),
    'adminCreateTestRecord' : IDL.Func(
        [
          ModelId,
          RouteId,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Float64,
          IDL.Float64,
          IDL.Vec(Issue),
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(TestingMode),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(TestPurpose),
          IDL.Opt(IDL.Int),
        ],
        [IDL.Variant({ 'ok' : TestRecord, 'err' : IDL.Text })],
        [],
      ),
    'changePassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createUserByAdmin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, UserRole],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'deleteRoute' : IDL.Func(
        [RouteId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteTestRecord' : IDL.Func(
        [RecordId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteUserByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteVehicleModel' : IDL.Func(
        [ModelId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getRiderRating' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Opt(RiderRating), 'err' : IDL.Text })],
        ['query'],
      ),
    'getRoute' : IDL.Func([RouteId], [IDL.Opt(Route)], ['query']),
    'getTestRecord' : IDL.Func(
        [RecordId],
        [IDL.Variant({ 'ok' : IDL.Opt(TestRecord), 'err' : IDL.Text })],
        ['query'],
      ),
    'getTopIssues' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Variant({
            'ok' : IDL.Vec(IDL.Tuple(IssueFlag, IDL.Nat)),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getUserByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVehicleModel' : IDL.Func([ModelId], [IDL.Opt(VehicleModel)], ['query']),
    'listAllUsers' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(UserProfile), 'err' : IDL.Text })],
        ['query'],
      ),
    'listRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
    'listTestRecords' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(TestRecord), 'err' : IDL.Text })],
        ['query'],
      ),
    'listTestRecordsByModel' : IDL.Func(
        [ModelId],
        [IDL.Variant({ 'ok' : IDL.Vec(TestRecord), 'err' : IDL.Text })],
        ['query'],
      ),
    'listTestRecordsByRider' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(TestRecord), 'err' : IDL.Text })],
        ['query'],
      ),
    'listTestRecordsByRoute' : IDL.Func(
        [RouteId],
        [IDL.Variant({ 'ok' : IDL.Vec(TestRecord), 'err' : IDL.Text })],
        ['query'],
      ),
    'listVehicleModels' : IDL.Func([], [IDL.Vec(VehicleModel)], ['query']),
    'loginWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'recalculateRiderRating' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : RiderRating, 'err' : IDL.Text })],
        [],
      ),
    'registerSelf' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'setAdminRatingForRider' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : RiderRating, 'err' : IDL.Text })],
        [],
      ),
    'submitTestRecord' : IDL.Func(
        [
          ModelId,
          RouteId,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Float64,
          IDL.Float64,
          IDL.Vec(Issue),
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(TestingMode),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(TestPurpose),
          IDL.Opt(IDL.Int),
        ],
        [IDL.Variant({ 'ok' : TestRecord, 'err' : IDL.Text })],
        [],
      ),
    'updateUserRole' : IDL.Func(
        [IDL.Principal, UserRole],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updateUserRoleByUsername' : IDL.Func(
        [IDL.Text, UserRole],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };