/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RiderRating {
    adminRating?: bigint;
    username: string;
    adminRatingComment?: string;
    aiScoreTimestamp?: Timestamp;
    aiScore?: number;
    aiScoreFactors?: AiScoreFactors;
    adminRatingTimestamp?: Timestamp;
}
export type Timestamp = bigint;
export type ModelId = bigint;
export type TestPurpose = {
    __kind__: "ComponentTest";
    ComponentTest: null;
} | {
    __kind__: "Range";
    Range: null;
} | {
    __kind__: "Durability";
    Durability: null;
} | {
    __kind__: "Others";
    Others: string;
};
export interface TestRecord {
    id: RecordId;
    photoUrls: Array<string>;
    rangeStartKm: number;
    vehicleModelName: string;
    startSoc?: number;
    stopSoc?: number;
    createdBy: Principal;
    coRiderWeight?: number;
    vehicleModelId: ModelId;
    routeName: string;
    testingMode?: TestingMode;
    issues: Array<Issue>;
    customRoute?: string;
    routeId: RouteId;
    rangeStopKm: number;
    topSpeedKmh: number;
    testPurpose?: TestPurpose;
    timestamp: Timestamp;
    riderName: string;
    avgSpeedKmh: number;
    dateOfRide?: Timestamp;
    riderWeight?: number;
}
export type RouteId = bigint;
export interface VehicleModel {
    id: ModelId;
    vehicleType: VehicleType;
    name: string;
    createdAt: Timestamp;
    specs: string;
}
export interface Issue {
    flag: IssueFlag;
    description: string;
}
export type RecordId = bigint;
export interface AiScoreFactors {
    behaviorScore: number;
    totalKm: number;
    issueCount: bigint;
    workingDays: bigint;
}
export type TestingMode = {
    __kind__: "Eco";
    Eco: null;
} | {
    __kind__: "Sport";
    Sport: null;
} | {
    __kind__: "City";
    City: null;
} | {
    __kind__: "Other";
    Other: string;
};
export interface UserProfile {
    adminRating?: bigint;
    principal: Principal;
    username?: string;
    adminRatingComment?: string;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    passwordHash?: string;
    aiScoreTimestamp?: Timestamp;
    aiScore?: number;
    aiScoreFactors?: AiScoreFactors;
    adminRatingTimestamp?: Timestamp;
}
export interface Route {
    id: RouteId;
    name: string;
    createdAt: Timestamp;
    description: string;
    distanceKm: number;
}
export enum IssueFlag {
    Safety = "Safety",
    Software = "Software",
    Mechanical = "Mechanical",
    Performance = "Performance",
    Electrical = "Electrical",
    Other = "Other"
}
export enum UserRole {
    Rider = "Rider",
    Analyst = "Analyst",
    Admin = "Admin"
}
export enum VehicleType {
    TwoWheeler = "TwoWheeler",
    ThreeWheeler = "ThreeWheeler"
}
export interface backendInterface {
    addRoute(name: string, description: string, distanceKm: number): Promise<{
        __kind__: "ok";
        ok: Route;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addVehicleModel(name: string, vehicleType: VehicleType, specs: string): Promise<{
        __kind__: "ok";
        ok: VehicleModel;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminCreateTestRecord(vehicleModelId: ModelId, routeId: RouteId, riderName: string, rangeStartKm: number, rangeStopKm: number, startSoc: number | null, stopSoc: number | null, topSpeedKmh: number, avgSpeedKmh: number, issues: Array<Issue>, photoUrls: Array<string> | null, testingMode: TestingMode | null, customRoute: string | null, riderWeight: number | null, coRiderWeight: number | null, testPurpose: TestPurpose | null, dateOfRide: bigint | null): Promise<{
        __kind__: "ok";
        ok: TestRecord;
    } | {
        __kind__: "err";
        err: string;
    }>;
    changePassword(username: string, currentPassword: string, newPassword: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createUserByAdmin(username: string, password: string, name: string, role: UserRole): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteRoute(id: RouteId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteTestRecord(id: RecordId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteUser(principal: Principal): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteUserByUsername(username: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteVehicleModel(id: ModelId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyProfile(): Promise<UserProfile | null>;
    getRiderRating(username: string): Promise<{
        __kind__: "ok";
        ok: RiderRating | null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getRoute(id: RouteId): Promise<Route | null>;
    getTestRecord(id: RecordId): Promise<{
        __kind__: "ok";
        ok: TestRecord | null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getTopIssues(limit: bigint): Promise<{
        __kind__: "ok";
        ok: Array<[IssueFlag, bigint]>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getUserByUsername(username: string): Promise<UserProfile | null>;
    getUserProfile(principal: Principal): Promise<UserProfile | null>;
    getVehicleModel(id: ModelId): Promise<VehicleModel | null>;
    listAllUsers(): Promise<{
        __kind__: "ok";
        ok: Array<UserProfile>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    listRoutes(): Promise<Array<Route>>;
    listTestRecords(): Promise<{
        __kind__: "ok";
        ok: Array<TestRecord>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    listTestRecordsByModel(modelId: ModelId): Promise<{
        __kind__: "ok";
        ok: Array<TestRecord>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    listTestRecordsByRider(riderName: string): Promise<{
        __kind__: "ok";
        ok: Array<TestRecord>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    listTestRecordsByRoute(routeId: RouteId): Promise<{
        __kind__: "ok";
        ok: Array<TestRecord>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    listVehicleModels(): Promise<Array<VehicleModel>>;
    loginWithCredentials(username: string, password: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    recalculateRiderRating(username: string): Promise<{
        __kind__: "ok";
        ok: RiderRating;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerSelf(name: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setAdminRatingForRider(username: string, rating: bigint, comment: string | null): Promise<{
        __kind__: "ok";
        ok: RiderRating;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitTestRecord(vehicleModelId: ModelId, routeId: RouteId, riderName: string, rangeStartKm: number, rangeStopKm: number, startSoc: number | null, stopSoc: number | null, topSpeedKmh: number, avgSpeedKmh: number, issues: Array<Issue>, photoUrls: Array<string> | null, testingMode: TestingMode | null, customRoute: string | null, riderWeight: number | null, coRiderWeight: number | null, testPurpose: TestPurpose | null, dateOfRide: bigint | null): Promise<{
        __kind__: "ok";
        ok: TestRecord;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateUserRole(principal: Principal, newRole: UserRole): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateUserRoleByUsername(username: string, newRole: UserRole): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AiScoreFactors as _AiScoreFactors, Issue as _Issue, IssueFlag as _IssueFlag, ModelId as _ModelId, RecordId as _RecordId, RiderRating as _RiderRating, Route as _Route, RouteId as _RouteId, TestPurpose as _TestPurpose, TestRecord as _TestRecord, TestingMode as _TestingMode, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, VehicleModel as _VehicleModel, VehicleType as _VehicleType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addRoute(arg0: string, arg1: string, arg2: number): Promise<{
        __kind__: "ok";
        ok: Route;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoute(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoute(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addVehicleModel(arg0: string, arg1: VehicleType, arg2: string): Promise<{
        __kind__: "ok";
        ok: VehicleModel;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addVehicleModel(arg0, to_candid_VehicleType_n2(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVehicleModel(arg0, to_candid_VehicleType_n2(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateTestRecord(arg0: ModelId, arg1: RouteId, arg2: string, arg3: number, arg4: number, arg5: number | null, arg6: number | null, arg7: number, arg8: number, arg9: Array<Issue>, arg10: Array<string> | null, arg11: TestingMode | null, arg12: string | null, arg13: number | null, arg14: number | null, arg15: TestPurpose | null, arg16: bigint | null): Promise<{
        __kind__: "ok";
        ok: TestRecord;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateTestRecord(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg6), arg7, arg8, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg14), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg15), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg16));
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateTestRecord(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg6), arg7, arg8, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg14), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg15), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg16));
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async changePassword(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.changePassword(arg0, arg1, arg2);
                return from_candid_variant_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePassword(arg0, arg1, arg2);
            return from_candid_variant_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUserByAdmin(arg0: string, arg1: string, arg2: string, arg3: UserRole): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserByAdmin(arg0, arg1, arg2, to_candid_UserRole_n42(this._uploadFile, this._downloadFile, arg3));
                return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserByAdmin(arg0, arg1, arg2, to_candid_UserRole_n42(this._uploadFile, this._downloadFile, arg3));
            return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteRoute(arg0: RouteId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRoute(arg0);
                return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRoute(arg0);
            return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTestRecord(arg0: RecordId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestRecord(arg0);
                return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestRecord(arg0);
            return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteUser(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteUserByUsername(arg0: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserByUsername(arg0);
                return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserByUsername(arg0);
            return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteVehicleModel(arg0: ModelId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVehicleModel(arg0);
                return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVehicleModel(arg0);
            return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiderRating(arg0: string): Promise<{
        __kind__: "ok";
        ok: RiderRating | null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiderRating(arg0);
                return from_candid_variant_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiderRating(arg0);
            return from_candid_variant_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoute(arg0: RouteId): Promise<Route | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoute(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoute(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestRecord(arg0: RecordId): Promise<{
        __kind__: "ok";
        ok: TestRecord | null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestRecord(arg0);
                return from_candid_variant_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestRecord(arg0);
            return from_candid_variant_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopIssues(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: Array<[IssueFlag, bigint]>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopIssues(arg0);
                return from_candid_variant_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopIssues(arg0);
            return from_candid_variant_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByUsername(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByUsername(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByUsername(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicleModel(arg0: ModelId): Promise<VehicleModel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicleModel(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicleModel(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllUsers(): Promise<{
        __kind__: "ok";
        ok: Array<UserProfile>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_variant_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_variant_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRoutes(): Promise<Array<Route>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRoutes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRoutes();
            return result;
        }
    }
    async listTestRecords(): Promise<{
        __kind__: "ok";
        ok: Array<TestRecord>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listTestRecords();
                return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTestRecords();
            return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTestRecordsByModel(arg0: ModelId): Promise<{
        __kind__: "ok";
        ok: Array<TestRecord>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listTestRecordsByModel(arg0);
                return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTestRecordsByModel(arg0);
            return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTestRecordsByRider(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<TestRecord>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listTestRecordsByRider(arg0);
                return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTestRecordsByRider(arg0);
            return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTestRecordsByRoute(arg0: RouteId): Promise<{
        __kind__: "ok";
        ok: Array<TestRecord>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listTestRecordsByRoute(arg0);
                return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTestRecordsByRoute(arg0);
            return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVehicleModels(): Promise<Array<VehicleModel>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVehicleModels();
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVehicleModels();
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginWithCredentials(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithCredentials(arg0, arg1);
                return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithCredentials(arg0, arg1);
            return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async recalculateRiderRating(arg0: string): Promise<{
        __kind__: "ok";
        ok: RiderRating;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recalculateRiderRating(arg0);
                return from_candid_variant_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recalculateRiderRating(arg0);
            return from_candid_variant_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerSelf(arg0: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerSelf(arg0);
                return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerSelf(arg0);
            return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAdminRatingForRider(arg0: string, arg1: bigint, arg2: string | null): Promise<{
        __kind__: "ok";
        ok: RiderRating;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminRatingForRider(arg0, arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminRatingForRider(arg0, arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitTestRecord(arg0: ModelId, arg1: RouteId, arg2: string, arg3: number, arg4: number, arg5: number | null, arg6: number | null, arg7: number, arg8: number, arg9: Array<Issue>, arg10: Array<string> | null, arg11: TestingMode | null, arg12: string | null, arg13: number | null, arg14: number | null, arg15: TestPurpose | null, arg16: bigint | null): Promise<{
        __kind__: "ok";
        ok: TestRecord;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestRecord(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg6), arg7, arg8, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg14), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg15), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg16));
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestRecord(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg6), arg7, arg8, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg14), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg15), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg16));
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserRole(arg0: Principal, arg1: UserRole): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n42(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n42(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserRoleByUsername(arg0: string, arg1: UserRole): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRoleByUsername(arg0, to_candid_UserRole_n42(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRoleByUsername(arg0, to_candid_UserRole_n42(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_IssueFlag_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IssueFlag): IssueFlag {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Issue_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Issue): Issue {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_RiderRating_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiderRating): RiderRating {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_TestPurpose_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestPurpose): TestPurpose {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_TestRecord_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestRecord): TestRecord {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TestingMode_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestingMode): TestingMode {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleModel_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleModel): VehicleModel {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TestingMode]): TestingMode | null {
    return value.length === 0 ? null : from_candid_TestingMode_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TestPurpose]): TestPurpose | null {
    return value.length === 0 ? null : from_candid_TestPurpose_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AiScoreFactors]): AiScoreFactors | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RiderRating]): RiderRating | null {
    return value.length === 0 ? null : from_candid_RiderRating_n55(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Route]): Route | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TestRecord]): TestRecord | null {
    return value.length === 0 ? null : from_candid_TestRecord_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VehicleModel]): VehicleModel | null {
    return value.length === 0 ? null : from_candid_VehicleModel_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecordId;
    photoUrls: Array<string>;
    rangeStartKm: number;
    vehicleModelName: string;
    startSoc: [] | [number];
    stopSoc: [] | [number];
    createdBy: Principal;
    coRiderWeight: [] | [number];
    vehicleModelId: _ModelId;
    routeName: string;
    testingMode: [] | [_TestingMode];
    issues: Array<_Issue>;
    customRoute: [] | [string];
    routeId: _RouteId;
    rangeStopKm: number;
    topSpeedKmh: number;
    testPurpose: [] | [_TestPurpose];
    timestamp: _Timestamp;
    riderName: string;
    avgSpeedKmh: number;
    dateOfRide: [] | [_Timestamp];
    riderWeight: [] | [number];
}): {
    id: RecordId;
    photoUrls: Array<string>;
    rangeStartKm: number;
    vehicleModelName: string;
    startSoc?: number;
    stopSoc?: number;
    createdBy: Principal;
    coRiderWeight?: number;
    vehicleModelId: ModelId;
    routeName: string;
    testingMode?: TestingMode;
    issues: Array<Issue>;
    customRoute?: string;
    routeId: RouteId;
    rangeStopKm: number;
    topSpeedKmh: number;
    testPurpose?: TestPurpose;
    timestamp: Timestamp;
    riderName: string;
    avgSpeedKmh: number;
    dateOfRide?: Timestamp;
    riderWeight?: number;
} {
    return {
        id: value.id,
        photoUrls: value.photoUrls,
        rangeStartKm: value.rangeStartKm,
        vehicleModelName: value.vehicleModelName,
        startSoc: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.startSoc)),
        stopSoc: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.stopSoc)),
        createdBy: value.createdBy,
        coRiderWeight: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.coRiderWeight)),
        vehicleModelId: value.vehicleModelId,
        routeName: value.routeName,
        testingMode: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.testingMode)),
        issues: from_candid_vec_n31(_uploadFile, _downloadFile, value.issues),
        customRoute: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.customRoute)),
        routeId: value.routeId,
        rangeStopKm: value.rangeStopKm,
        topSpeedKmh: value.topSpeedKmh,
        testPurpose: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.testPurpose)),
        timestamp: value.timestamp,
        riderName: value.riderName,
        avgSpeedKmh: value.avgSpeedKmh,
        dateOfRide: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.dateOfRide)),
        riderWeight: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.riderWeight))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flag: _IssueFlag;
    description: string;
}): {
    flag: IssueFlag;
    description: string;
} {
    return {
        flag: from_candid_IssueFlag_n34(_uploadFile, _downloadFile, value.flag),
        description: value.description
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adminRating: [] | [bigint];
    principal: Principal;
    username: [] | [string];
    adminRatingComment: [] | [string];
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    passwordHash: [] | [string];
    aiScoreTimestamp: [] | [_Timestamp];
    aiScore: [] | [number];
    aiScoreFactors: [] | [_AiScoreFactors];
    adminRatingTimestamp: [] | [_Timestamp];
}): {
    adminRating?: bigint;
    principal: Principal;
    username?: string;
    adminRatingComment?: string;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    passwordHash?: string;
    aiScoreTimestamp?: Timestamp;
    aiScore?: number;
    aiScoreFactors?: AiScoreFactors;
    adminRatingTimestamp?: Timestamp;
} {
    return {
        adminRating: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.adminRating)),
        principal: value.principal,
        username: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.username)),
        adminRatingComment: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.adminRatingComment)),
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n48(_uploadFile, _downloadFile, value.role),
        passwordHash: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.passwordHash)),
        aiScoreTimestamp: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.aiScoreTimestamp)),
        aiScore: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.aiScore)),
        aiScoreFactors: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.aiScoreFactors)),
        adminRatingTimestamp: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.adminRatingTimestamp))
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adminRating: [] | [bigint];
    username: string;
    adminRatingComment: [] | [string];
    aiScoreTimestamp: [] | [_Timestamp];
    aiScore: [] | [number];
    aiScoreFactors: [] | [_AiScoreFactors];
    adminRatingTimestamp: [] | [_Timestamp];
}): {
    adminRating?: bigint;
    username: string;
    adminRatingComment?: string;
    aiScoreTimestamp?: Timestamp;
    aiScore?: number;
    aiScoreFactors?: AiScoreFactors;
    adminRatingTimestamp?: Timestamp;
} {
    return {
        adminRating: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.adminRating)),
        username: value.username,
        adminRatingComment: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.adminRatingComment)),
        aiScoreTimestamp: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.aiScoreTimestamp)),
        aiScore: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.aiScore)),
        aiScoreFactors: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.aiScoreFactors)),
        adminRatingTimestamp: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.adminRatingTimestamp))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ModelId;
    vehicleType: _VehicleType;
    name: string;
    createdAt: _Timestamp;
    specs: string;
}): {
    id: ModelId;
    vehicleType: VehicleType;
    name: string;
    createdAt: Timestamp;
    specs: string;
} {
    return {
        id: value.id,
        vehicleType: from_candid_VehicleType_n7(_uploadFile, _downloadFile, value.vehicleType),
        name: value.name,
        createdAt: value.createdAt,
        specs: value.specs
    };
}
function from_candid_tuple_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_IssueFlag, bigint]): [IssueFlag, bigint] {
    return [
        from_candid_IssueFlag_n34(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Route;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Route;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TestRecord;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TestRecord;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_TestRecord_n25(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Eco: null;
} | {
    Sport: null;
} | {
    City: null;
} | {
    Other: string;
}): {
    __kind__: "Eco";
    Eco: null;
} | {
    __kind__: "Sport";
    Sport: null;
} | {
    __kind__: "City";
    City: null;
} | {
    __kind__: "Other";
    Other: string;
} {
    return "Eco" in value ? {
        __kind__: "Eco",
        Eco: value.Eco
    } : "Sport" in value ? {
        __kind__: "Sport",
        Sport: value.Sport
    } : "City" in value ? {
        __kind__: "City",
        City: value.City
    } : "Other" in value ? {
        __kind__: "Other",
        Other: value.Other
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Safety: null;
} | {
    Software: null;
} | {
    Mechanical: null;
} | {
    Performance: null;
} | {
    Electrical: null;
} | {
    Other: null;
}): IssueFlag {
    return "Safety" in value ? IssueFlag.Safety : "Software" in value ? IssueFlag.Software : "Mechanical" in value ? IssueFlag.Mechanical : "Performance" in value ? IssueFlag.Performance : "Electrical" in value ? IssueFlag.Electrical : "Other" in value ? IssueFlag.Other : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ComponentTest: null;
} | {
    Range: null;
} | {
    Durability: null;
} | {
    Others: string;
}): {
    __kind__: "ComponentTest";
    ComponentTest: null;
} | {
    __kind__: "Range";
    Range: null;
} | {
    __kind__: "Durability";
    Durability: null;
} | {
    __kind__: "Others";
    Others: string;
} {
    return "ComponentTest" in value ? {
        __kind__: "ComponentTest",
        ComponentTest: value.ComponentTest
    } : "Range" in value ? {
        __kind__: "Range",
        Range: value.Range
    } : "Durability" in value ? {
        __kind__: "Durability",
        Durability: value.Durability
    } : "Others" in value ? {
        __kind__: "Others",
        Others: value.Others
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _VehicleModel;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: VehicleModel;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_VehicleModel_n5(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n45(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Rider: null;
} | {
    Analyst: null;
} | {
    Admin: null;
}): UserRole {
    return "Rider" in value ? UserRole.Rider : "Analyst" in value ? UserRole.Analyst : "Admin" in value ? UserRole.Admin : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [] | [_RiderRating];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: RiderRating | null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_opt_n54(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [] | [_TestRecord];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TestRecord | null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_opt_n59(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<[_IssueFlag, bigint]>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<[IssueFlag, bigint]>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n61(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_UserProfile>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<UserProfile>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n65(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_TestRecord>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<TestRecord>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n67(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _RiderRating;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: RiderRating;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_RiderRating_n55(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    TwoWheeler: null;
} | {
    ThreeWheeler: null;
}): VehicleType {
    return "TwoWheeler" in value ? VehicleType.TwoWheeler : "ThreeWheeler" in value ? VehicleType.ThreeWheeler : value;
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Issue>): Array<Issue> {
    return value.map((x)=>from_candid_Issue_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_IssueFlag, bigint]>): Array<[IssueFlag, bigint]> {
    return value.map((x)=>from_candid_tuple_n62(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TestRecord>): Array<TestRecord> {
    return value.map((x)=>from_candid_TestRecord_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VehicleModel>): Array<VehicleModel> {
    return value.map((x)=>from_candid_VehicleModel_n5(_uploadFile, _downloadFile, x));
}
function to_candid_IssueFlag_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IssueFlag): _IssueFlag {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Issue_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Issue): _Issue {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_TestPurpose_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestPurpose): _TestPurpose {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_TestingMode_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestingMode): _TestingMode {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<string> | null): [] | [Array<string>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestingMode | null): [] | [_TestingMode] {
    return value === null ? candid_none() : candid_some(to_candid_TestingMode_n17(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestPurpose | null): [] | [_TestPurpose] {
    return value === null ? candid_none() : candid_some(to_candid_TestPurpose_n21(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flag: IssueFlag;
    description: string;
}): {
    flag: _IssueFlag;
    description: string;
} {
    return {
        flag: to_candid_IssueFlag_n13(_uploadFile, _downloadFile, value.flag),
        description: value.description
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IssueFlag): {
    Safety: null;
} | {
    Software: null;
} | {
    Mechanical: null;
} | {
    Performance: null;
} | {
    Electrical: null;
} | {
    Other: null;
} {
    return value == IssueFlag.Safety ? {
        Safety: null
    } : value == IssueFlag.Software ? {
        Software: null
    } : value == IssueFlag.Mechanical ? {
        Mechanical: null
    } : value == IssueFlag.Performance ? {
        Performance: null
    } : value == IssueFlag.Electrical ? {
        Electrical: null
    } : value == IssueFlag.Other ? {
        Other: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "Eco";
    Eco: null;
} | {
    __kind__: "Sport";
    Sport: null;
} | {
    __kind__: "City";
    City: null;
} | {
    __kind__: "Other";
    Other: string;
}): {
    Eco: null;
} | {
    Sport: null;
} | {
    City: null;
} | {
    Other: string;
} {
    return value.__kind__ === "Eco" ? {
        Eco: value.Eco
    } : value.__kind__ === "Sport" ? {
        Sport: value.Sport
    } : value.__kind__ === "City" ? {
        City: value.City
    } : value.__kind__ === "Other" ? {
        Other: value.Other
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "ComponentTest";
    ComponentTest: null;
} | {
    __kind__: "Range";
    Range: null;
} | {
    __kind__: "Durability";
    Durability: null;
} | {
    __kind__: "Others";
    Others: string;
}): {
    ComponentTest: null;
} | {
    Range: null;
} | {
    Durability: null;
} | {
    Others: string;
} {
    return value.__kind__ === "ComponentTest" ? {
        ComponentTest: value.ComponentTest
    } : value.__kind__ === "Range" ? {
        Range: value.Range
    } : value.__kind__ === "Durability" ? {
        Durability: value.Durability
    } : value.__kind__ === "Others" ? {
        Others: value.Others
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): {
    TwoWheeler: null;
} | {
    ThreeWheeler: null;
} {
    return value == VehicleType.TwoWheeler ? {
        TwoWheeler: null
    } : value == VehicleType.ThreeWheeler ? {
        ThreeWheeler: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    Rider: null;
} | {
    Analyst: null;
} | {
    Admin: null;
} {
    return value == UserRole.Rider ? {
        Rider: null
    } : value == UserRole.Analyst ? {
        Analyst: null
    } : value == UserRole.Admin ? {
        Admin: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Issue>): Array<_Issue> {
    return value.map((x)=>to_candid_Issue_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
